name: Build/release

on: push

jobs:
  release:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - run: |
          npm ci --prefix ./pt-main/ ./pt-main
          npm --prefix run dist
        env:
          CI_BUILD_TAG: ${{ github.ref_type	== 'tag' && github.ref_name }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
